# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:00"
      day: "friday"
    assignees:
      - "efa2d19"
    reviewers:
      - "efa2d19"
    commit-message:
      prefix: "poetry"
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:00"
      day: "friday"
